### ISSUE TITLE
[BUG] exceed maximum number of tokens

### ISSUE THREAD

**Issue by yalattas** [yalattas/mindmate#9]
**Describe the bug**
openai throwing an error in case user exceeds the maximum allowed token per respond

**To Reproduce**
pass `--max-token 5000`  flag

**Expected behavior**
To work or partition to handle the error

**Screenshots**
```
Traceback (most recent call last):
  File "/home/yalattas/.local/lib/python3.8/site-packages/mindmate/services/openai.py", line 81, in ask_ai_with_stream
    completion = openai.Completion.create(
  File "/home/yalattas/.local/lib/python3.8/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/yalattas/.local/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/yalattas/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/yalattas/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/home/yalattas/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 5018 tokens (18 in your prompt; 5000 for the completion). Please reduce your prompt; or completion length.
```

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Version v0.1.6

**Version**
- v0.1.6

**Comment by yalattas** [comment]
Closes by: 431e5d0fc9233c8ced01a58d89df5b191c2ce76a
